/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NftsRouteImport } from './routes/nfts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpotIndexRouteImport } from './routes/spot/index'
import { Route as SpotSymbolRouteImport } from './routes/spot/$symbol'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsRoute = NftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotIndexRoute = SpotIndexRouteImport.update({
  id: '/spot/',
  path: '/spot/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotSymbolRoute = SpotSymbolRouteImport.update({
  id: '/spot/$symbol',
  path: '/spot/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nfts': typeof NftsRoute
  '/portfolio': typeof PortfolioRoute
  '/transactions': typeof TransactionsRoute
  '/spot/$symbol': typeof SpotSymbolRoute
  '/spot': typeof SpotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nfts': typeof NftsRoute
  '/portfolio': typeof PortfolioRoute
  '/transactions': typeof TransactionsRoute
  '/spot/$symbol': typeof SpotSymbolRoute
  '/spot': typeof SpotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nfts': typeof NftsRoute
  '/portfolio': typeof PortfolioRoute
  '/transactions': typeof TransactionsRoute
  '/spot/$symbol': typeof SpotSymbolRoute
  '/spot/': typeof SpotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nfts'
    | '/portfolio'
    | '/transactions'
    | '/spot/$symbol'
    | '/spot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nfts' | '/portfolio' | '/transactions' | '/spot/$symbol' | '/spot'
  id:
    | '__root__'
    | '/'
    | '/nfts'
    | '/portfolio'
    | '/transactions'
    | '/spot/$symbol'
    | '/spot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NftsRoute: typeof NftsRoute
  PortfolioRoute: typeof PortfolioRoute
  TransactionsRoute: typeof TransactionsRoute
  SpotSymbolRoute: typeof SpotSymbolRoute
  SpotIndexRoute: typeof SpotIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts': {
      id: '/nfts'
      path: '/nfts'
      fullPath: '/nfts'
      preLoaderRoute: typeof NftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot/': {
      id: '/spot/'
      path: '/spot'
      fullPath: '/spot'
      preLoaderRoute: typeof SpotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot/$symbol': {
      id: '/spot/$symbol'
      path: '/spot/$symbol'
      fullPath: '/spot/$symbol'
      preLoaderRoute: typeof SpotSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NftsRoute: NftsRoute,
  PortfolioRoute: PortfolioRoute,
  TransactionsRoute: TransactionsRoute,
  SpotSymbolRoute: SpotSymbolRoute,
  SpotIndexRoute: SpotIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
