/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ChartsIndexImport } from './routes/charts/index'
import { Route as ChartsCoinImport } from './routes/charts/$coin'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChartsIndexRoute = ChartsIndexImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRoute,
} as any)

const ChartsCoinRoute = ChartsCoinImport.update({
  id: '/charts/$coin',
  path: '/charts/$coin',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/charts/$coin': {
      id: '/charts/$coin'
      path: '/charts/$coin'
      fullPath: '/charts/$coin'
      preLoaderRoute: typeof ChartsCoinImport
      parentRoute: typeof rootRoute
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charts/$coin': typeof ChartsCoinRoute
  '/charts': typeof ChartsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts/$coin': typeof ChartsCoinRoute
  '/charts': typeof ChartsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/charts/$coin': typeof ChartsCoinRoute
  '/charts/': typeof ChartsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/charts/$coin' | '/charts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/charts/$coin' | '/charts'
  id: '__root__' | '/' | '/charts/$coin' | '/charts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartsCoinRoute: typeof ChartsCoinRoute
  ChartsIndexRoute: typeof ChartsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartsCoinRoute: ChartsCoinRoute,
  ChartsIndexRoute: ChartsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/charts/$coin",
        "/charts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/charts/$coin": {
      "filePath": "charts/$coin.tsx"
    },
    "/charts/": {
      "filePath": "charts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
